package com.svw.uc.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BaseService service = new BaseService();
 * IBase portType = service.getBasePort();
 * portType.queryAuthProduct(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BaseService", targetNamespace = "http://impl.ws.uc.svw.com/", wsdlLocation = "http://121.40.207.195:8080/locater/services/BaseService?wsdl")
public class BaseService extends Service {

	private final static URL BASESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.svw.uc.ws.impl.BaseService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.svw.uc.ws.impl.BaseService.class.getResource(".");
			url = new URL(baseUrl, "http://121.40.207.195:8080/locater/services/BaseService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://121.40.207.195:8080/locater/services/BaseService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BASESERVICE_WSDL_LOCATION = url;
	}

	public BaseService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BaseService() {
		super(BASESERVICE_WSDL_LOCATION, new QName("http://impl.ws.uc.svw.com/", "BaseService"));
	}

	/**
	 * 
	 * @return returns IBase
	 */
	@WebEndpoint(name = "BasePort")
	public IBase getBasePort() {
		return super.getPort(new QName("http://impl.ws.uc.svw.com/", "BasePort"), IBase.class);
	}

}
