package com.svw.uc.ws.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.svw.uc.ws.BackHaukResult;
import com.svw.uc.ws.TtBackhaulPo;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IBackhaul", targetNamespace = "http://ws.uc.svw.com/")
public interface IBackhaul {

	/**
	 * 
	 * @param ttBackhaulPO
	 * @return returns com.svw.uc.ws.BackHaukResult
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "save", targetNamespace = "http://ws.uc.svw.com/", className = "com.svw.uc.ws.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://ws.uc.svw.com/", className = "com.svw.uc.ws.SaveResponse")
	public BackHaukResult save(@WebParam(name = "ttBackhaulPO", targetNamespace = "") TtBackhaulPo ttBackhaulPO);

}
